export const Client = [
  // ========== FULL-STACK PROJECTS (WITH DATABASES) ==========
  {
    name: "Monark FX",
    logo: "/project/monark.png",
    description: "Financial services platform with payment integration & live Zoom sessions",
    techStack: ["React", "NextJS", "NodeJS", "PostgreSQL", "Razorpay", "Zoom SDK", "CI/CD (GitHub Actions)"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/monark.jpeg",
    demoLink: "https://monarkfx.com",
  },
  {
    name: "Panacea Medcare",
    logo: "/project/panacea.png",
    description: "Healthcare services platform with appointment booking & patient engagement",
    techStack: ["Next.js", "React", "Tailwind CSS", "SEO Optimization"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/panacea.jpeg",
    demoLink: "https://panaceamedcare.com",
  },
  {
    name: "Shrestha Academy",
    logo: "/project/shrestha.png",
    description: "Educational platform with course management & student onboarding",
    techStack: ["Next.js", "React", "Node.js", "PostgreSQL"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/shreeshta.jpeg",
    demoLink: "https://shresthaacademy.com",
  },
  {
    name: "Desi To Global Travel",
    logo: "/project/travel.png",
    description: "Travel agency platform with tour packages & booking inquiries",
    techStack: ["Next.js", "React", "Tailwind CSS", "Framer Motion"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/global.jpeg",
    demoLink: "https://www.desitoglobaltravel.com",
  },
  {
    name: "Genuine Nutrition",
    logo: "/project/genuine.png",
    description: "Nutrition supplement e-commerce with product catalog & payments",
    techStack: ["Next.js", "React", "Razorpay", "Prisma"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Genuine%20Nutrition.png",
    demoLink: "https://genuinenutrition.com",
  },
  {
    name: "Bansuri Vidya",
    logo: "/project/bansuri.png",
    description: "Online music learning platform for flute education with course modules",
    techStack: ["Next.js", "React", "Tailwind CSS", "Node.js"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Bansuri%20Vidya.png",
    demoLink: "https://bansurividya.com",
  },
  {
    name: "Kaal Tools",
    logo: "/project/kaal.png",
    description: "Industrial tools e-commerce with product catalog & order management",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Kaal%20Tools.png",
    demoLink: "https://kaaltools.com",
  },
  {
    name: "DJ Challenger",
    logo: "/project/dj.png",
    description: "Entertainment & DJ booking platform with event showcase",
    techStack: ["Next.js", "React", "Tailwind CSS", "Framer Motion"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/DJ%20Challenger.png",
    demoLink: "https://djchallenger.in",
  },
  // {
  //   name: "DFixKart",
  //   logo: "/project/dfixkart.png",
  //   description: "Online marketplace with product listings, cart & payment integration",
  //   techStack: ["Next.js", "React", "Node.js", "Razorpay", "Prisma"],
  //   imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/difx.jpeg",
  //   demoLink: "https://dfixkart.com",
  // },
  {
    name: "Genuine Pharmacy",
    logo: "/project/pharmacy.png",
    description: "Pharmacy e-commerce with medicine catalog & order system",
    techStack: ["Next.js", "React", "Node.js", "Prisma"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Genuine%20Pharmacy.png",
    demoLink: "https://genuinepharmacy.com",
  },
  {
    name: "Surat Cloth House",
    logo: "/project/surat.png",
    description: "Textile & clothing e-commerce with catalog & bulk ordering",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Surat%20Cloth%20House.png",
    demoLink: "https://suratclothhouse.com",
  },
  {
    name: "Muscle-X",
    logo: "/project/musclex.png",
    description: "Fitness supplement e-commerce with product listings & checkout",
    techStack: ["Next.js", "React", "Tailwind CSS", "Razorpay"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Muscle-X.png",
    demoLink: "https://muscle-x.com",
  },
  {
    name: "Being Genuine Nutrition",
    logo: "/project/being.png",
    description: "Health supplement brand website with product catalog & orders",
    techStack: ["Next.js", "React", "Tailwind CSS", "Razorpay"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Being%20Genuine%20Nutrition.png",
    demoLink: "https://beinggenuinenutrition.com",
  },
  {
    name: "Pro Housing",
    logo: "/project/prohousing.png",
    description: "Real estate platform with property listings & advanced search filters",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Pro%20Housing.png",
    demoLink: "https://prohousing.in",
  },
  {
    name: "Nifty Nitesh",
    logo: "/project/nifty.webp",
    description: "Stock market learning platform with dynamic content & stock insights",
    techStack: ["Next.js", "React", "Google Sheet (DB)", "Cloudinary"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/nifty.jpeg",
    demoLink: "https://niftynitesh.com",
  },
  {
    name: "Indian Law Masters",
    logo: "/project/lawmasters.png",
    description: "Legal services platform for law consultancy with case management",
    techStack: ["Next.js", "React", "Node.js", "PostgreSQL"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Indian%20Law%20Masters.png",
    demoLink: "https://indianlawmasters.com",
  },
  {
    name: "Adyashakti",
    logo: "/project/adya.png",
    description: "Non-profit organization website with donation integration",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Adyashakti.png",
    demoLink: "https://adyashakti.org",
  },
  {
    name: "UMSC",
    logo: "/project/umsc.png",
    description: "Educational/corporate platform with services & contact management",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/UMSC.png",
    demoLink: "https://umsc.in",
  },
  {
    name: "Belvore Realty",
    logo: "/project/belvore.png",
    description: "Real estate company website with property listings",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Belvore%20Realty.png",
    demoLink: "https://belvorealty.com",
  },
  {
    name: "KN Medico Legal",
    logo: "/project/kn.png",
    description: "Medical-legal consultancy website with service listings",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/KN%20Medico%20Legal.png",
    demoLink: "https://knmedicolegal.com",
  },
  {
    name: "Borrowww",
    logo: "/project/borrowww.png",
    description: "Borrowing/lending services platform with user management",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Borrowww.png",
    demoLink: "https://borrowww.com",
  },
  {
    name: "Bohra Property",
    logo: "/project/bohra.png",
    description: "Real estate listing platform with property search & inquiry management",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Bohra%20Property.png",
    demoLink: "https://bohraproperty.com",
  },

  // ========== STATIC WEBSITES ==========
  {
    name: "SLJ Solutions",
    logo: "/project/slj.png",
    description: "IT solutions company with service catalog & lead generation",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/slj.jpeg",
    demoLink: "https://sljsolutions.com",
  },
  {
    name: "Grox Media",
    logo: "/project/grox.png",
    description: "Digital media agency website with portfolio showcase & services",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Grox%20Media.png",
    demoLink: "https://groxmedia.in",
  },
  {
    name: "EOAN",
    logo: "/project/11th.png",
    description: "Corporate business website with service listings & company profile",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/EOAN.png",
    demoLink: "https://eoan.in",
  },
  {
    name: "Air Harbours",
    logo: "/project/air.png",
    description: "Aviation services platform with service listings & client management",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Air%20Harbours.png",
    demoLink: "https://www.airharbours.com",
  },
  {
    name: "Clinica Dental & Skin",
    logo: "/project/clinica.png",
    description: "Dental & skin clinic website with appointment booking & services",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Clinica%20Dental%20%26%20Skin.png",
    demoLink: "https://clinicadentalandskin.com",
  },
  {
    name: "Raven Law",
    logo: "/project/raven.png",
    description: "Law firm website with legal services & client portal",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Raven%20Law.png",
    demoLink: "https://ravenlaw.in",
  },
  {
    name: "Shubh Law Firm",
    logo: "/project/shubh.png",
    description: "Law firm website with legal services & case consultation",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Shubh%20Law%20Firm.png",
    demoLink: "https://shubhlawfirm.com",
  },
  {
    name: "Pirguna Air Systems",
    logo: "/project/pirguna.png",
    description: "Air systems & HVAC company website with product catalog",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Pirguna%20Air%20Systems.png",
    demoLink: "https://pirgunairsystems.com",
  },
  {
    name: "Go Delivery Group",
    logo: "/project/godelivery.png",
    description: "Delivery & logistics company website with service tracking",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Go%20Delivery%20Group.png",
    demoLink: "https://godeliverygroup.com",
  },
  {
    name: "Ananya Bhatnagar",
    logo: "/project/ananya.png",
    description: "Personal/portfolio website for professional profile",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Ananya%20Bhatnagar.png",
    demoLink: "https://ananyabhatnagar.org",
  },
  {
    name: "Paws Friend",
    logo: "/project/paws.png",
    description: "Pet care services website with adoption & services",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Paws%20Friend.png",
    demoLink: "https://pawsfriend.in",
  },
  {
    name: "JP Infotech",
    logo: "/project/jp.png",
    description: "IT company website with technology services & solutions",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/JP%20Infotech.png",
    demoLink: "https://jpinfotech.net",
  },
  {
    name: "Invest NICP",
    logo: "/project/invest.png",
    description: "Investment advisory platform with financial resources",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Invest%20NICP.png",
    demoLink: "https://investnicp.com",
  },
  {
    name: "Satya CS",
    logo: "/project/satya.png",
    description: "Corporate services website with consulting & company registration",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    imageSrc: "https://pub-a3d2b35862c1483894ffbee942bb995e.r2.dev/Satya%20CS.png",
    demoLink: "https://satyacs.com",
  },
];
